version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 5000:5000
    volumes:
    - .:/django_microservice
    container_name: django_microservice_container
    command: django r 0.0.0.0:5000
